# Generated by Django 4.2.1 on 2023-05-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birthDate', models.DateField()),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
