# Generated by Django 4.2.1 on 2023-05-24 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('IS', 'Information System'), ('DS', 'Decision Support'), ('AI', 'Artificial Intelligence')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('1', 'one'), ('2', 'tow'), ('3', 'three'), ('4', 'four')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=15, null=True),
        ),
    ]
