# Generated by Django 4.2.1 on 2023-06-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_student_department_student_gender_student_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('General', 'General'), ('CS', 'Computer Science'), ('IT', 'Information Technology'), ('IS', 'Information System'), ('DS', 'Decision Support'), ('AI', 'Artificial Intelligence')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four')], max_length=10, null=True),
        ),
    ]
